const users = [{
        userId: "sOMZlZMtZdQXmUS1uMa054dU7zx1",
        username: "joey",
        email: "joeytribbiani@gmail.com",
        fullName: "joey tribbiani",
        biography: "I look a woman up and down and say, ‘Hey, how you doin’?'",
        avatar: "/public/img/avatars/joey.jpg",
        latitude: "40.7128",
        longitude: "74.0060",
        following: ["2", "6", "3"],
        followers: ["2", "3", "4", "5", "6"],
        isPrivate: false,
        isVerified: false,
        created_at: Date.now(),
    },
    {
        userId: "2",
        username: "chandler",
        email: "chandlerbing@gmail.com",
        fullName: "Chandler Bing",
        biography: "When I first meet somebody it’s usually panic, anxiety, and a great deal of sweating.",
        avatar: "/public/img/avatars/chandler.jpg",
        latitude: "40.7128",
        longitude: "74.0060",
        following: [],
        followers: ["sOMZlZMtZdQXmUS1uMa054dU7zx1", "3"],
        isPrivate: true,
        isVerified: false,
        created_at: Date.now(),
    },
    {
        userId: "3",
        username: "ross",
        email: "drrossgeller@gmail.com",
        fullName: "Dr Ross Geller",
        biography: "If you’re going to call me names, I would prefer ‘Ross, the Divorce Force.’ It’s just cooler.",
        avatar: "/public/img/avatars/ross.jpg",
        latitude: "40.7128",
        longitude: "74.0060",
        following: [],
        followers: ["sOMZlZMtZdQXmUS1uMa054dU7zx1"],
        isPrivate: false,
        isVerified: false,
        created_at: Date.now(),
    },
    {
        userId: "4",
        username: "monica",
        email: "monicageller@gmail.com",
        fullName: "Monica Geller",
        biography: "Welcome to the real world. It sucks. You’re gonna love it.",
        avatar: "/public/img/avatars/monica.jpg",
        latitude: "40.7128",
        longitude: "74.0060",
        following: [],
        followers: ["sOMZlZMtZdQXmUS1uMa054dU7zx1"],
        isPrivate: false,
        isVerified: false,
        created_at: Date.now(),
    },
    {
        userId: "5",
        username: "rachel",
        email: "rachelgreen@gmail.com",
        fullName: "Rachel Green",
        biography: "Just so you know, it’s not that common, it doesn’t happen to every guy, and it is a big deal!",
        avatar: "/public/img/avatars/rachel.jpg",
        latitude: "40.7128",
        longitude: "74.0060",
        following: [],
        followers: ["sOMZlZMtZdQXmUS1uMa054dU7zx1"],
        isPrivate: false,
        isVerified: false,
        created_at: Date.now(),
    },
    {
        userId: "6",
        username: "phoebe",
        email: "rphoebebuffay@gmail.com",
        fullName: "Phoebe Buffay",
        biography: "Smelly cat, smelly cat, what are they feeding you? / Smelly cat, smelly cat, it’s not your fault.",
        avatar: "/public/img/avatars/phoebe.jpg",
        latitude: "40.7128",
        longitude: "74.0060",
        following: [],
        followers: ["sOMZlZMtZdQXmUS1uMa054dU7zx1"],
        isPrivate: false,
        isVerified: true,
        created_at: Date.now(),
    },
];

// Chandler Bing: When I first meet somebody it’s usually panic, anxiety, and a great deal of sweating.
// Dr Ross Geller: If you’re going to call me names, I would prefer ‘Ross, the Divorce Force.’ It’s just cooler.
// Phoebe Buffay: Smelly cat, smelly cat, what are they feeding you? / Smelly cat, smelly cat, it’s not your fault.
// Rachel Green: Just so you know, it’s not that common, it doesn’t happen to every guy, and it is a big deal!
// Monica Geller: Welcome to the real world. It sucks. You’re gonna love it.

export default users;